name: Run Script with ads on Push and Daily Schedule

on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

jobs:
  run-script:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  

    - name: Install the 'ads' library
      run: | 
        pip install --upgrade pip 
        pip install ads

    - name: Run the script
      run: |
        python bin/get_ads.py  # Replace with the path to your script file

    - name: push changes
      run: |
        git pull origin master
        git add *.bib
        git -c user.name='farnikn' -c user.email='farnik.nikakhtar@yale.edu' commit -m "updating bib file"
        git push origin master